### ISSUE TITLE
Dosn't work

### ISSUE THREAD

**Issue by MatinDehghanian** [abolfazlalz/folder-creator#1]
![image](https://user-images.githubusercontent.com/69871290/117051498-dd201b80-ad2b-11eb-86a6-2e32143c99b3.png)

**Comment by abolfazlalz** [comment]
in project bara sherkate, ba`ad exe niaz ndsht
chon mehdi neghaban khodesh python dare.

**Comment by abolfazlalz** [comment]
but thanks for your review

**Comment by abolfazlalz** [comment]
lotfan dg to project public fosh nade 😆
